services:
  db:
    image: postgres:17.5
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
